"""init tables

Revision ID: b001b59147a5
Revises: 
Create Date: 2026-01-18 07:45:07.916537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b001b59147a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_job_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_jobs_posted_at'), 'jobs', ['posted_at'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_source_job_id'), 'jobs', ['source_job_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('q', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('posted_after', sa.Date(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('seen_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('search_name', sa.String(), nullable=False),
    sa.Column('job_uid', sa.String(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_uid'], ['jobs.uid'], ),
    sa.ForeignKeyConstraint(['search_name'], ['saved_searches.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_name', 'job_uid', name='uq_seen_search_job')
    )
    op.create_index(op.f('ix_seen_jobs_job_uid'), 'seen_jobs', ['job_uid'], unique=False)
    op.create_index(op.f('ix_seen_jobs_search_name'), 'seen_jobs', ['search_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seen_jobs_search_name'), table_name='seen_jobs')
    op.drop_index(op.f('ix_seen_jobs_job_uid'), table_name='seen_jobs')
    op.drop_table('seen_jobs')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_jobs_source_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_posted_at'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
